[package]
name = "hanoi"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "775edc615ecec631d65b6180dbcc7bc26c3abc26"}
